/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.kislay.goasat.gui;

import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import net.kislay.goasat.XmlConfig;

/**
 *
 * @author KISLAY
 */
public class SoundChooserMain extends javax.swing.JFrame implements ActionListener {

    private XmlConfig config;
    public final static String CONFIG_FILE = "conf" + File.separator + "peers.xml";
    private net.kislay.goasat.Logger logger;

    /**
     * Creates new form NewJFrame1
     */
    public SoundChooserMain() {
        config = new XmlConfig("."+File.separator + CONFIG_FILE, this.logger);
         logger = new net.kislay.goasat.Logger("."+File.separator);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        miconofftogglebtn = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridonepanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        gridtwopanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        gridthreepanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GoAsat       Desinged With Love        -Kislay");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(241, 240, 126));
        jButton1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton1.setText("Instant Pause Voice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        miconofftogglebtn.setBackground(new java.awt.Color(100, 193, 93));
        miconofftogglebtn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        miconofftogglebtn.setText("Mic Enabled");
        miconofftogglebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miconofftogglebtnActionPerformed(evt);
            }
        });
        jPanel3.add(miconofftogglebtn);

        gridonepanel.setBackground(new java.awt.Color(52, 49, 111));
        gridonepanel.setForeground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(gridonepanel);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane4.setBackground(new java.awt.Color(173, 147, 63));

        gridtwopanel.setBackground(new java.awt.Color(175, 168, 89));

        javax.swing.GroupLayout gridtwopanelLayout = new javax.swing.GroupLayout(gridtwopanel);
        gridtwopanel.setLayout(gridtwopanelLayout);
        gridtwopanelLayout.setHorizontalGroup(
            gridtwopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        gridtwopanelLayout.setVerticalGroup(
            gridtwopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(gridtwopanel);

        jSplitPane2.setLeftComponent(jScrollPane4);

        gridthreepanel.setBackground(new java.awt.Color(80, 138, 75));

        javax.swing.GroupLayout gridthreepanelLayout = new javax.swing.GroupLayout(gridthreepanel);
        gridthreepanel.setLayout(gridthreepanelLayout);
        gridthreepanelLayout.setHorizontalGroup(
            gridthreepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        gridthreepanelLayout.setVerticalGroup(
            gridthreepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(gridthreepanel);

        jSplitPane2.setRightComponent(jScrollPane5);

        jSplitPane1.setRightComponent(jSplitPane2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miconofftogglebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miconofftogglebtnActionPerformed
        if (miconofftogglebtn.isSelected()) {
            MainFrame.MIC_ON = true;
            miconofftogglebtn.setText("Mic Enabled");//100,193,93
            miconofftogglebtn.setBackground(new java.awt.Color(100, 193, 93));
        } else {
            MainFrame.MIC_ON = false;
            miconofftogglebtn.setText("Mic Disabled");
            MainFrame.filename = config.getPauseFile();
            miconofftogglebtn.setBackground(new java.awt.Color(246, 74, 89));
        }
    }//GEN-LAST:event_miconofftogglebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            MainFrame.filein = new FileInputStream(config.getPauseFile());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseSound.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoundChooserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoundChooserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoundChooserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoundChooserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            SoundChooserMain frame1 = new SoundChooserMain();

            public void run() {
                frame1.setVisible(true);
                frame1.AddBut();
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridonepanel;
    private javax.swing.JPanel gridthreepanel;
    private javax.swing.JPanel gridtwopanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToggleButton miconofftogglebtn;
    // End of variables declaration//GEN-END:variables
    public void AddBut() {
        GridLayout layout = new GridLayout(15, 10, 2, 2);
        gridonepanel.setLayout(layout);
        gridtwopanel.setLayout(layout);
        gridthreepanel.setLayout(layout);
        File files = new File(config.getHomeFolder());
        File list[];
        list = files.listFiles();
        int len = 0;
        len = list.length;
        for (int i = 0; i < len; i++) {
            JButton but = new JButton(list[i].getName());

            but.setFont(new java.awt.Font("Arial", Font.PLAIN, 12)); // NOI18N
            //but.setSize(50, 50);

            but.addActionListener(this);
            if (list[i].getName().endsWith("_1")) {
                but.setBackground(new java.awt.Color(129, 169, 201));
                gridonepanel.add(but);
            } else if (list[i].getName().endsWith("_2")) {
                but.setBackground(new java.awt.Color(152, 211, 127));
                gridtwopanel.add(but);
            } else if (list[i].getName().endsWith("_3")) {
                but.setBackground(new java.awt.Color(254, 173, 95));
                gridthreepanel.add(but);
            }

        }

//           jButton2.setBackground(new java.awt.Color(129, 169, 201));
//        jButton2.setText("jButton2");
//
//        jButton3.setBackground(new java.awt.Color(152, 211, 127));
//        jButton3.setText("jButton3");
//
//        jButton4.setBackground(new java.awt.Color(254, 173, 95));
        jScrollPane1.setSize(1024, 740);
        // jPanel1.setSize(1024,640);
        this.setSize(1200, 840);
        this.repaint();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String eventname = e.getActionCommand();
        try {
            MainFrame.filein = new FileInputStream(config.getHomeFolder()+File.separator + eventname);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChooseSound.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
